version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
      day: "sunday"
    groups:
      patches:
        update-types:
          - "patch"
    ignore:
      - dependency-name: "@angular*"
        update-types: [ "version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch" ]
      - dependency-name: "*"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
      day: "sunday"
    groups:
      patches:
        update-types:
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
      day: "sunday"
