name: Dependency Submission

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ '**/pom.xml', '.github/workflows/dependency-submission.yml' ]

concurrency:
  group: '${{ github.workflow }}: ${{ github.ref }}'
  cancel-in-progress: true

jobs:
  dependency-submission:
    name: Dependency Submission
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Java Setup
        id: java-setup
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          # cache: 'maven' takes too long
          overwrite-settings: 'false'
      - name: Info
        id: info
        run: |
          java -version
          ./mvnw -version
          echo "MAVEN_OPTS: $MAVEN_OPTS"
      - name: Dependency Submission
        id: dependency-submission
        uses: advanced-security/maven-dependency-submission-action@v5
